import Icon from 'react-native-vector-icons/Ionicons';
import Icon2 from 'react-native-vector-icons/FontAwesome5';
import appColors from './appColors';

export const catData = [
  {
    title: 'developers',
    imgage: require('../assets/images/dev.jpg'),
  },
  {
    title: 'designers',
    imgage: require('../assets/images/figma.jpg'),
  },
  {
    title: 'traders',
    imgage: require('../assets/images/treding.jpg'),
  },

  {
    title: 'crickters',
    imgage: require('../assets/images/cricketer.jpg'),
  },
  {
    title: 'teachers',
    imgage: require('../assets/images/teacher.jpg'),
  },
  {
    title: 'editors',
    imgage: require('../assets/images/editor.jpg'),
  },
];

export const bannerData = [
  {
    title: 'Developers',
    imgage: '../../assets/images/img1.webp',
  },
  {
    title: 'Designers',
    imgage: '../../assets/images/img2.webp',
  },
  {
    title: 'Traders',
    imgage: '../../assets/images/img3.webp',
  },
  {
    title: 'Teachers',
    imgage: '../../assets/images/img4.webp',
  },
  {
    title: 'Crickters',
    imgage: '../../assets/images/img5.webp',
  },
  {
    title: 'Editors',
    imgage: '../../assets/images/img6.webp',
  },
];

export const sizeChart = [
  {size: 'S', chest: 34, waist: 26, hips: 36},
  {size: 'M', chest: 36, waist: 28, hips: 38},
  {size: 'L', chest: 38, waist: 30, hips: 40},
  {size: 'XL', chest: 40, waist: 32, hips: 42},
];

export const dummyData = [
  {
    _id: '65a6a0c6eaeb104ee74e31d8',
    product_name: 'postman',
    category: 'Hoodies',
    price: 2000,
    discount: 5,
    description: 'postman hoodies for all back-end developers',
    images: [
      'http://res.cloudinary.com/devtrendy/image/upload/v1705418921/Hoodies/ttnqg37dt0g8yuyfanv4.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705418924/Hoodies/l1uqxtvvw8htunjicbgl.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705418927/Hoodies/zxq4wcil9lt4b0mviijj.png',
    ],
    coverImage:
      'http://res.cloudinary.com/devtrendy/image/upload/v1705579959/Hoodies/bl8m6dymndiaxyywfdsd.png',
    createdAt: '2024-01-16T15:29:10.885Z',
    updatedAt: '2024-01-18T12:12:43.221Z',
    __v: 0,
  },
  {
    _id: '65a6a115eaeb104ee74e31de',
    product_name: 'docker',
    category: 'Hoodies',
    price: 2500,
    discount: 10,
    description: 'This is Best Hoodies for all DevOps Engineers',
    images: [
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419004/Hoodies/skyou97g6jsdsqcknlgi.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419006/Hoodies/gbvtgmaa7gzimpzlergv.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419008/Hoodies/nzlpqsvzssfwltz78gqr.png',
    ],
    coverImage:
      'http://res.cloudinary.com/devtrendy/image/upload/v1705579996/Hoodies/jwg3vog8f9yfiryfarzb.png',
    createdAt: '2024-01-16T15:30:29.999Z',
    updatedAt: '2024-01-18T12:13:22.454Z',
    __v: 0,
  },
  {
    _id: '65a6a17ceaeb104ee74e31e0',
    product_name: 'linux',
    category: 'Hoodies',
    price: 2000,
    discount: 5,
    description: 'These Hoodies for all Hackers and as well as Linux OS Users',
    images: [
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419084/Hoodies/z21bkjchrq8rc9nfua0j.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419087/Hoodies/md9ghnokmsaa83miz3tz.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419091/Hoodies/qspxxaoyyrgdkwzdledj.png',
    ],
    coverImage:
      'http://res.cloudinary.com/devtrendy/image/upload/v1705580033/Hoodies/fymlh8ad3913bf3yzphm.png',
    createdAt: '2024-01-16T15:32:12.948Z',
    updatedAt: '2024-01-18T12:13:56.722Z',
    __v: 0,
  },
  {
    _id: '65a6a279eaeb104ee74e31ee',
    product_name: 'vs code || t-shirt',
    category: 'T-Shirt',
    price: 2400,
    discount: 5,
    description: 'Vs code CodeEditors Choice',
    images: [
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419367/T-Shirt/ktqmq6xoigck3dkplwc8.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419370/T-Shirt/ptncutnui1riu1nntvjp.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419372/T-Shirt/dk2bzavcsibrnoy0hdp0.png',
    ],
    coverImage:
      'http://res.cloudinary.com/devtrendy/image/upload/v1705580079/T-Shirt/zhh657j7bt0ohzmqbeky.png',
    createdAt: '2024-01-16T15:36:25.397Z',
    updatedAt: '2024-01-18T12:14:43.040Z',
    __v: 0,
  },
  {
    _id: '65a6a316eaeb104ee74e31f0',
    product_name: 'mongodb || t-shirt',
    category: 'T-Shirt',
    price: 1500,
    discount: 4,
    description:
      'MongoDb users Choice .MongoDB is a schema-less database, which means the database can manage data without the need for a blueprint.',
    images: [
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419439/T-Shirt/ehswhrntsyy4tayuwq1l.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419441/T-Shirt/qkfnchlmtgre5iubwdsu.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419444/T-Shirt/xxcixo9s3lbhz97tq7od.png',
    ],
    coverImage:
      'http://res.cloudinary.com/devtrendy/image/upload/v1705580104/T-Shirt/hzlxfjbhjj9zzjhbaz7x.png',
    createdAt: '2024-01-16T15:39:02.786Z',
    updatedAt: '2024-01-18T12:15:10.520Z',
    __v: 0,
  },
  {
    _id: '65a6a361eaeb104ee74e31f2',
    product_name: '404 error code',
    category: 'T-Shirt',
    price: 3000,
    discount: 15,
    description:
      'The 404 code means that a server could not find a client-requested webpage. Variations of the error message include "404 Error," "404 Page Not Found" and "The requested URL was not found',
    images: [
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419589/T-Shirt/qzpzkcr5vbiwbd2vmzfu.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419591/T-Shirt/f2z1pzrxivu1yz776gnl.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419593/T-Shirt/jrauggd3vx4exr20twvp.png',
    ],
    coverImage:
      'http://res.cloudinary.com/devtrendy/image/upload/v1705580125/T-Shirt/ffnuht5fsubmklefa0ro.png',
    createdAt: '2024-01-16T15:40:17.528Z',
    updatedAt: '2024-01-18T12:15:29.555Z',
    __v: 0,
  },
  {
    _id: '65a6a3b1eaeb104ee74e31f4',
    product_name: 'nodejs|| t-shirt',
    category: 'T-Shirt',
    price: 1500,
    discount: 5,
    description:
      'Node. js (Node) is an Open Source, cross-platform runtime environment for executing JavaScript code. Node is used extensively for server-side programming',
    images: [
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419666/T-Shirt/cp8eimvxwzs8ew9gqgfi.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419668/T-Shirt/gxonftikdpb7qovwde7t.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1705419671/T-Shirt/jqiloftruyhcs7dsifkj.png',
    ],
    coverImage:
      'http://res.cloudinary.com/devtrendy/image/upload/v1705580146/T-Shirt/cx9tmvckyfr83wdes7fk.png',
    createdAt: '2024-01-16T15:41:37.302Z',
    updatedAt: '2024-01-18T12:15:49.704Z',
    __v: 0,
  },
  {
    _id: '65b7659f64e6b6e0e18cfe4a',
    product_name: 'javascript',
    category: 'Hoodies',
    price: 1200,
    discount: 5,
    description:
      't4jhwdeim asodwei0eqw pqwoewqoie mqwoieqwy8eqwiue asod9as9-em asidqw0epqw',
    images: [
      'http://res.cloudinary.com/devtrendy/image/upload/v1706517899/Hoodies/nfd5rur3b4rlcbhoa15k.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1706517900/Hoodies/beadrj1kppk3heyetyfl.png',
      'http://res.cloudinary.com/devtrendy/image/upload/v1706517901/Hoodies/fcf8gyjhifzqyxh4bnf6.png',
    ],
    coverImage:
      'http://res.cloudinary.com/devtrendy/image/upload/v1706517888/Hoodies/tnzbozuiy6rfn59igkmf.png',
    createdAt: '2024-01-29T08:45:19.020Z',
    updatedAt: '2024-01-29T08:45:19.020Z',
    __v: 0,
  },
];

export const countryCodes = [
  {name: 'United States', code: 'US', phoneCode: '+1'},
  {name: 'Canada', code: 'CA', phoneCode: '+1'},
  {name: 'United Kingdom', code: 'GB', phoneCode: '+44'},
  {name: 'Germany', code: 'DE', phoneCode: '+49'},
  {name: 'France', code: 'FR', phoneCode: '+33'},
  {name: 'Japan', code: 'JP', phoneCode: '+81'},
  {name: 'Australia', code: 'AU', phoneCode: '+61'},
  {name: 'Brazil', code: 'BR', phoneCode: '+55'},
  {name: 'India', code: 'IN', phoneCode: '+91'},
  {name: 'China', code: 'CN', phoneCode: '+86'},
  {name: 'Russia', code: 'RU', phoneCode: '+7'},
  {name: 'South Africa', code: 'ZA', phoneCode: '+27'},
  {name: 'Mexico', code: 'MX', phoneCode: '+52'},
  {name: 'Italy', code: 'IT', phoneCode: '+39'},
  {name: 'Spain', code: 'ES', phoneCode: '+34'},
  {name: 'South Korea', code: 'KR', phoneCode: '+82'},
  {name: 'Netherlands', code: 'NL', phoneCode: '+31'},
  {name: 'Canada', code: 'CA', phoneCode: '+1'},
  {name: 'Sweden', code: 'SE', phoneCode: '+46'},
  {name: 'Norway', code: 'NO', phoneCode: '+47'},
  {name: 'Denmark', code: 'DK', phoneCode: '+45'},
  {name: 'Finland', code: 'FI', phoneCode: '+358'},
  {name: 'Switzerland', code: 'CH', phoneCode: '+41'},
  {name: 'Singapore', code: 'SG', phoneCode: '+65'},
  {name: 'New Zealand', code: 'NZ', phoneCode: '+64'},
  {name: 'Argentina', code: 'AR', phoneCode: '+54'},
  {name: 'Turkey', code: 'TR', phoneCode: '+90'},
  {name: 'Saudi Arabia', code: 'SA', phoneCode: '+966'},
  {name: 'Egypt', code: 'EG', phoneCode: '+20'},
  {name: 'Nigeria', code: 'NG', phoneCode: '+234'},
  {name: 'Kenya', code: 'KE', phoneCode: '+254'},
];

export const indian_cities = [
  'Mumbai',
  'Delhi',
  'Bangalore',
  'Hyderabad',
  'Ahmedabad',
  'Chennai',
  'Kolkata',
  'Surat',
  'Pune',
  'Jaipur',
  'Lucknow',
  'Kanpur',
  'Nagpur',
  'Visakhapatnam',
  'Indore',
  'Thane',
  'Bhopal',
  'Patna',
  'Vadodara',
  'Ghaziabad',
  'Ludhiana',
  'Agra',
  'Nashik',
  'Faridabad',
  'Meerut',
  'Rajkot',
  'Varanasi',
  'Srinagar',
  'Aurangabad',
  'Dhanbad',
  'Amritsar',
  'Navi Mumbai',
  'Allahabad',
  'Ranchi',
  'Howrah',
  'Jabalpur',
  'Gwalior',
  'Vijayawada',
  'Jodhpur',
  'Madurai',
  'Raipur',
  'Kota',
  'Guwahati',
  'Chandigarh',
  'Solapur',
  'Hubli-Dharwad',
  'Bareilly',
  'Moradabad',
  'Mysore',
  'Gurgaon',
  'Aligarh',
  'Jalandhar',
  'Tiruchirappalli',
  'Bhubaneswar',
  'Salem',
  'Warangal',
  'Guntur',
  'Bhiwandi',
  'Saharanpur',
  'Gorakhpur',
  'Bikaner',
  'Amravati',
  'Noida',
  'Jamshedpur',
  'Bhilai',
  'Cuttack',
  'Firozabad',
  'Kochi',
  'Nellore',
  'Bhavnagar',
  'Dehradun',
  'Durgapur',
  'Asansol',
  'Rourkela',
  'Nanded',
  'Kolhapur',
  'Ajmer',
  'Akola',
  'Gulbarga',
  'Jamnagar',
  'Ujjain',
  'Loni',
  'Siliguri',
  'Jhansi',
  'Ulhasnagar',
  'Jammu',
  'Sangli-Miraj & Kupwad',
  'Nellore',
  'Belgaum',
  'Mangalore',
  'Ambattur',
  'Tirunelveli',
  'Malegaon',
  'Gaya',
  'Jalgaon',
  'Udaipur',
  'Maheshtala',
  'Tirupur',
  'Davanagere',
  'Kozhikode',
  'Akola',
  'Kurnool',
  'Bokaro Steel City',
  'Rajahmundry',
  'Ballari',
  'Agartala',
  'Bhagalpur',
  'Latur',
  'Dhule',
  'Korba',
  'Bhilwara',
  'Berhampur',
  'Muzaffarpur',
  'Ahmednagar',
  'Mathura',
  'Kollam',
  'Avadi',
  'Kadapa',
  'Anantapur',
  'Kamarhati',
  'Bilaspur',
  'Shahjahanpur',
  'Satara',
  'Bijapur',
  'Rampur',
  'Shivamogga',
  'Chandrapur',
  'Junagadh',
  'Thrissur',
  'Alwar',
  'Bardhaman',
  'Kulti',
  'Nizamabad',
  'Parbhani',
  'Tumkur',
  'Khammam',
  'Ozhukarai',
  'Bihar Sharif',
  'Panipat',
  'Darbhanga',
  'Bally',
  'Aizawl',
  'Dewas',
  'Ichalkaranji',
  'Karnal',
  'Bathinda',
  'Jalna',
  'Eluru',
  'Kirari Suleman Nagar',
  'Barasat',
  'Purnia',
  'Satna',
  'Mau',
  'Sonipat',
  'Farrukhabad',
  'Sagar',
  'Rourkela',
  'Durg',
  'Imphal',
  'Ratlam',
  'Hapur',
  'Anantapur',
  'Arrah',
  'Karimnagar',
  'Etawah',
  'Bharatpur',
  'Begusarai',
  'New Delhi',
  'Chhapra',
  'Kadapa',
  'Ramagundam',
  'Pali',
  'Hosur',
  'Ambarnath',
  'Bhimavaram',
  'Ongole',
  'Deoghar',
  'Chandannagar',
  'Haldia',
  'Hindupur',
  'Nagaon',
  'Kharagpur',
  'Sasaram',
  'Dibrugarh',
  'Shimla',
  'Gudivada',
  'Hubballi',
  'Junagadh',
  'Alappuzha',
  'Barasat',
  'Guna',
  'Gandhidham',
  'Godhra',
  'Khadki',
  'Bhimavaram',
  'Bulandshahr',
  'Navsari',
  'Madhyamgram',
  'Bhatpara',
  'Vapi',
  'Vadakara',
  'Baleshwar',
  'Sambalpur',
  'Port Blair',
  'Yavatmal',
  'Munger',
  'Panchkula',
  'Kulti',
  'Purnia',
  'Satara',
  'Bhind',
  'Gondiya',
  'Tiruvannamalai',
  'Banda',
  'Serampore',
  'Haldia',
  'Sambalpur',
  'Hoshiarpur',
  'Bahraich',
  'Suryapet',
  'Miryalaguda',
  'Karaikudi',
  'Anantnag',
  'Bhind',
  'Bhuj',
  'Modinagar',
  'Shivpuri',
  'Bathinda',
  'Azamgarh',
  'Palghar',
  'Damoh',
  'Bhusawal',
  'Singrauli',
  'Baranagar',
  'Bharuch',
  'Nadiad',
  'Karimnagar',
  'Haridwar',
  'Nangloi Jat',
  'Thanjavur',
  'Purulia',
  'Patan',
  'Navadwip',
  'Sirsa',
  'Yamunanagar',
  'Pali',
  'Munger',
  'Rewa',
  'Etah',
  'Dehri',
  'Madhyamgram',
  'Raiganj',
  'Serampore',
  'Ambikapur',
  'Meerut',
  'Vizianagaram',
  'Bettiah',
  'Motihari',
  'Nagapattinam',
  'Raichur',
  'Guntakal',
  'Srikakulam',
  'Shimoga',
  'Balurghat',
  'Sikar',
  'Panvel',
  'Orai',
  'Gonda',
  'Pilibhit',
  'Dimapur',
  'Hajipur',
  'Kohima',
  'Bhadrak',
  'Kishanganj',
  'Jind',
  'Tonk',
  'Tenali',
  'Sikar',
  'Jamalpur',
];

const indianStates = [
  {
    state: 'Arunachal Pradesh',
    cities: ['Itanagar', 'Naharlagun', 'Pasighat', 'Roing', 'Ziro'],
  },
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];

export const accountMenu = [
  {
    title: 'Orders',
    icon: <Icon2 name="shipping-fast" size={24} color={appColors.appRed} />,
  },
  {
    title: 'Wishlist',
    icon: <Icon2 name="heart" size={24} color={appColors.appRed} />,
  },
  {
    title: 'Coupons',
    icon: <Icon2 name="file-invoice" size={24} color={appColors.appRed} />,
  },
  {
    title: 'Help Center',
    icon: <Icon2 name="headset" size={24} color={appColors.appRed} />,
  },
];

//onsole.log(indianStates); // Output: ["Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", ...]
